apps:
  - script   : ./server.js
    name     : 'node_example-app'
    instances: 1
    exec_mode: cluster
    watch: false
    env:
      NODE_ENV: development
      PORT: 3000
    env_staging:
      NODE_ENV: staging
      PORT: 12345
    env_production:
      NODE_ENV: production
      PORT: 12345
